FROM php:8.2-alpine
RUN apk update && apk add --no-cache \
    git \
    curl \
    zip \
    unzip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-scripts
COPY . .    
EXPOSE 8080
CMD ["php", "-S", "0.0.0.0:5003", "microservicioGPC.php"]